version: "3"
services:
    db:
        container_name: menu_db
        image: mysql:5.7
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
        healthcheck:
            test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
            timeout: 4s
            retries: 60
    service:
        container_name: menu_service
        links:
            - db
        depends_on:
            db:
                condition: service_healthy
        image: piratux/menu-web-service
        ports:
            - "5000:5000"
